---
- hosts: DEV
  become: yes

  tasks:
   - name: Install Apache.
     yum:
       name:
         - httpd
         - httpd-devel
       state: present
   - name: Copy configuration files.
     copy:
       src: "{{ item.src }}"
       dest: "{{ item.dest }}" 
       owner: root
       group: root
       mode: 0644
     with_item:
       - src: httpd.conf
         dest: /etc/httpd/conf/httpd.conf
       - src: httpd-vhost.conf
         dest: /etc/httpd/conf/httpd-vhost.conf
   - name: make sure Apache is started now at boot
     service: name=httpd state=started enabled=yes            
          